[window]
padding = { x = 0, y = 0 }
decorations = "Full"
dynamic_padding = false
blur = true

[font]
normal = { family = "Cascadia Mono NF", style = "Regular" }
size = 11.0

[general]
live_config_reload = true

