vim.call('plug#begin')

Plug('tpope/vim-fugitive')
Plug('lewis6991/gitsigns.nvim')
Plug('tpope/vim-surround')
Plug('tpope/vim-repeat')
Plug('tpope/vim-abolish')
Plug('preservim/nerdcommenter')
Plug('loctvl842/monokai-pro.nvim')
Plug('itchyny/lightline.vim')
Plug('nvim-telescope/telescope.nvim', { tag = '0.1.8' })
Plug('nvim-lua/plenary.nvim')
Plug('nvim-treesitter/nvim-treesitter', { ['do'] = ':TSUpdate' }) 
Plug('edkolev/tmuxline.vim')
Plug('neovim/nvim-lspconfig')
Plug('ms-jpq/coq_nvim', { branch = 'coq' })
Plug('ms-jpq/coq.artifacts', { branch = 'artifacts' })
Plug('ms-jpq/chadtree')
Plug('nvim-lua/popup.nvim')
Plug('williamboman/mason.nvim')
Plug('williamboman/mason-lspconfig.nvim')
Plug('github/copilot.vim')
Plug('dense-analysis/ale')
Plug('kosayoda/nvim-lightbulb')
Plug('tris203/hawtkeys.nvim')

vim.call('plug#end')
